name: Refresh Stars Badge
on:
  workflow_dispatch:

jobs:
  update_badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Stars Badge
        run: |
          STARS_COUNT=$(curl -s https://api.github.com/repos/laitco/tailscale-healthcheck | jq -r '.stargazers_count')
          sed -i "s|<img src=\"https://img.shields.io/github/stars/laitco/tailscale-healthcheck\".*|<img src=\"https://img.shields.io/github/stars/laitco/tailscale-healthcheck\" alt=\"GitHub Stars\">|" README.md

      - name: Check for Changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes to commit." && echo "::set-output name=changes::false";
          else
            echo "::set-output name=changes::true";
          fi

      - name: Commit and Push Changes
        if: ${{ steps.check_changes.outputs.changes == 'true' }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update Stars Badge"
          git push